### ISSUE TITLE
Cannot set property 'strictMode' of undefined

### ISSUE THREAD

**Issue by mathieug** [bugsnag/bugsnag-node#58]
```
TypeError: Cannot set property 'strictMode' of undefined
    at /app/node_modules/bugsnag/lib/utils.js:62:31
    at Array.forEach (native)
    at Object.Utils.cloneObject (/app/node_modules/bugsnag/lib/utils.js:51:26)
    at /app/node_modules/bugsnag/lib/utils.js:57:43
    at Array.forEach (native)
    at Object.Utils.cloneObject (/app/node_modules/bugsnag/lib/utils.js:51:26)
    at /app/node_modules/bugsnag/lib/utils.js:57:43
    at Array.forEach (native)
    at Object.Utils.cloneObject (/app/node_modules/bugsnag/lib/utils.js:51:26)
    at new Notification (/app/node_modules/bugsnag/lib/notification.js:23:31)
    at Object.Bugsnag.notify (/app/node_modules/bugsnag/lib/bugsnag.js:101:20)
    at Bugsnag.errorHandler (/app/node_modules/bugsnag/lib/bugsnag.js:108:13)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:300:13)
    at /app/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)
    at next (/app/node_modules/express/lib/router/index.js:261:10)
    at /app/node_modules/express/lib/router/index.js:603:15
    at next (/app/node_modules/express/lib/router/index.js:246:14)
    at next (/app/node_modules/express/lib/router/route.js:100:14)
    at ...
```

**Comment by mathieug** [comment]
I got this error when I set an instance of a mongoose document in `bugsnag.requestData`.

**Comment by keeganlow** [comment]
Hey @mathieug, could you try updating to version 1.6.4 and see if the issue has been resolved. Thanks!

**Comment by kattrali** [comment]
Closing as resolved, can reopen with additional feedback.
